export let GET_PARTY_PENDING="GET_PARTY_PENDING";
export let GET_PARTY_SUCCESS="GET_PARTY_SUCCESS";
export let GET_PARTY_ERROR="GET_PARTY_ERROR";

export let POST_PARTY_PENDING="POST_PARTY_PENDING";
export let POST_PARTY_SUCCESS="POST_PARTY_SUCCESS";
export let POST_PARTY_ERROR="POST_PARTY_ERROR";

export let DELETE_PARTY_PENDING="DELETE_PARTY_PENDING";
export let DELETE_PARTY_SUCCESS="DELETE_PARTY_SUCCESS";
export let DELETE_PARTY_ERROR="DELETE_PARTY_ERROR";

export let GET_VOTER_PENDING="GET_VOTER_PENDING";
export let GET_VOTER_SUCCESS="GET_VOTER_SUCCESS";
export let GET_VOTER_ERROR="GET_VOTER_ERROR";

export let POST_VOTER_PENDING="POST_VOTER_PENDING";
export let POST_VOTER_SUCCESS="POST_VOTER_SUCCESS";
export let POST_VOTER_ERROR="POST_VOTER_ERROR";

export let DELETE_VOTER_PENDING="DELETE_VOTER_PENDING";
export let DELETE_VOTER_SUCCESS="DELETE_VOTER_SUCCESS";
export let DELETE_VOTER_ERROR="DELETE_VOTER_ERROR";